@isTest
public class OrderHandlerTest {
  
    // @isTest
    // public static void insertNewOrder() {
    //     //Test SetEffectiveDate Trigger
    //     Test.startTest();
    //     Order newOrder = new Order(OrderNumber = 1);
    //     insert newOrder;

    //     Order insertedOrder = [SELECT EffectiveDate FROM Order WHERE OrderNumber = :newOrder.OrderNumber LIMIT 1];
    //     System.assertEquals(date.today(), insertedOrder);
    //     Test.stopTest();
    // }



    // @isTest
    // public static void updateActivatedOrder() {
    //     //Test Prevent Changes Trigger
    //     Test.startTest();
    //     Boolean updateUnsuccessful = false;

    //     Order finishedOrder = new Order(OrderNumber = 1);
    //     finishedOrder.status = 'Activated';
    //     insert finishedOrder;

    //     finishedOrder.BillingAddress = 'Test Address';

    //     try {
    //         update finishedOrder;
    //     } catch (Exception e) {
    //         updateUnsuccessful = true;
    //     }
    //     System.assertEquals(true, updateUnsuccessful);
    //     Test.stopTest();
//}





}
